name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build APK
      run: ./gradlew assembleRelease
    
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: bubble-app-release
        path: app/build/outputs/apk/release/app-release.apk
    
    - name: Create Release
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: softprops/action-gh-release@v1
      with:
        files: app/build/outputs/apk/release/app-release.apk
        tag_name: v${{ github.run_number }}
        name: Release v${{ github.run_number }}
        body: |
          ## Bubble Floating App APK
          
          ### Features:
          - Floating bubble overlay
          - Draggable bubble
          - Tap to show "Hello Sagar"
          - Minimal size (~1.5MB)
          
          ### Installation:
          1. Enable "Install from unknown sources"
          2. Install this APK
          3. Grant overlay permission
          4. Enjoy the floating bubble!
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}